// ============================================================
// Imran Salara MD Bot — utility tools (30)
// Uses free public APIs where sensible; works offline otherwise.
// ============================================================

const crypto = require('crypto');

// In-memory per-user storage (resets on restart — noted in replies).
const store = { notes: {}, todos: {} };
const userBox = (box, from) => {
  if (!store[box][from]) store[box][from] = [];
  return store[box][from];
};

const needArgs = (args, usage) =>
  args.length ? null : `✏️ Please provide input.\nUsage: ${usage}`;

async function fetchJson(url, opts = {}) {
  const res = await fetch(url, opts);
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res.json();
}

// --- Safe math evaluator: only digits and operators allowed ---
function safeCalc(expr) {
  const clean = expr.replace(/\s+/g, '');
  if (!/^[0-9+\-*/%().]+$/.test(clean) || !clean) throw new Error('bad');
  // eslint-disable-next-line no-new-func
  const val = Function(`"use strict"; return (${clean});`)();
  if (typeof val !== 'number' || !isFinite(val)) throw new Error('bad');
  return Math.round(val * 1e10) / 1e10;
}

const MORSE = { a: '.-', b: '-...', c: '-.-.', d: '-..', e: '.', f: '..-.', g: '--.', h: '....', i: '..', j: '.---', k: '-.-', l: '.-..', m: '--', n: '-.', o: '---', p: '.--.', q: '--.-', r: '.-.', s: '...', t: '-', u: '..-', v: '...-', w: '.--', x: '-..-', y: '-.--', z: '--..', 0: '-----', 1: '.----', 2: '..---', 3: '...--', 4: '....-', 5: '.....', 6: '-....', 7: '--...', 8: '---..', 9: '----.', ' ': '/' };
const MORSE_REV = Object.fromEntries(Object.entries(MORSE).map(([k, v]) => [v, k]));
const toMorse = (t) => t.toLowerCase().split('').map((ch) => MORSE[ch] || '?').join(' ');
const fromMorse = (t) => t.trim().split(/\s+/).map((c) => MORSE_REV[c] || '?').join('');

const ROMAN_URDU_WORDS = ['hai', 'nahi', 'nahin', 'kya', 'kaise', 'kyun', 'tum', 'aap', 'mein', 'main', 'aur', 'lekin', 'magar', 'bohat', 'bahut', 'acha', 'accha', 'shukriya', 'khuda', 'allah', 'mujhe', 'tumhe', 'aapko', 'kaise', 'ho', 'tha', 'thi', 'hain', 'wala', 'wali', 'liye', 'saath', 'sath'];

const commands = [
  { name: 'calc', description: 'Calculate a math expression', category: 'tools', usage: '.calc 12*8+5',
    execute: (args) => {
      const e = needArgs(args, '.calc <expression>'); if (e) return e;
      try { return `🧮 *Result:* ${safeCalc(args.join(' '))}`; }
      catch { return '❌ Invalid expression. Use digits and + - * / % ( ).'; }
    } },
  { name: 'qr', description: 'Generate a QR code image', category: 'tools', usage: '.qr <text>',
    execute: (args) => {
      const e = needArgs(args, '.qr <text>'); if (e) return e;
      const data = encodeURIComponent(args.join(' '));
      return { text: `🔳 *QR Code generated by Imran Salara MD Bot*`, image: `https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=${data}` };
    } },
  { name: 'translate', description: 'Translate text (free API)', category: 'tools', usage: '.translate <lang> <text>  (e.g. .translate ur hello)',
    execute: async (args) => {
      if (args.length < 2) return '🌍 Usage: .translate <lang-code> <text>\nExample: .translate ur Good morning\nCodes: ur, en, ar, fr, es, de…';
      const target = args[0].toLowerCase();
      const text = args.slice(1).join(' ');
      try {
        const d = await fetchJson(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=auto|${target}`);
        const out = d?.responseData?.translatedText;
        if (!out) throw new Error('empty');
        return `🌍 *Translation → ${target}:*\n\n${out}`;
      } catch { return '❌ Translation service unavailable right now. Try again later.'; }
    } },
  { name: 'wiki', description: 'Wikipedia summary', category: 'tools', usage: '.wiki <topic>',
    execute: async (args) => {
      const e = needArgs(args, '.wiki <topic>'); if (e) return e;
      try {
        const d = await fetchJson(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(args.join(' '))}`);
        if (d.type === 'disambiguation' || !d.extract) throw new Error('none');
        return `📚 *${d.title}*\n\n${d.extract.slice(0, 1200)}${d.content_urls?.desktop?.page ? `\n\n🔗 ${d.content_urls.desktop.page}` : ''}`;
      } catch { return '❌ No Wikipedia article found for that topic.'; }
    } },
  { name: 'define', description: 'English word definition', category: 'tools', usage: '.define <word>',
    execute: async (args) => {
      const e = needArgs(args, '.define <word>'); if (e) return e;
      try {
        const d = await fetchJson(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(args[0])}`);
        const entry = d[0];
        const defs = (entry.meanings || []).slice(0, 3).map((m) => `• _${m.partOfSpeech}_: ${m.definitions[0]?.definition || ''}`).join('\n');
        return `📖 *${entry.word}* ${entry.phonetic || ''}\n\n${defs || 'No definition found.'}`;
      } catch { return '❌ No definition found for that word.'; }
    } },
  { name: 'weather', description: 'Current weather for a city', category: 'tools', usage: '.weather <city>',
    execute: async (args) => {
      const e = needArgs(args, '.weather <city>'); if (e) return e;
      const key = process.env.WEATHER_API_KEY;
      if (!key) return '🌦️ Weather needs a free OpenWeatherMap key.\nAsk the bot owner to set WEATHER_API_KEY.';
      try {
        const d = await fetchJson(`https://api.openweathermap.org/data/2.5/weather?q=${encodeURIComponent(args.join(' '))}&appid=${key}&units=metric`);
        return `🌦️ *Weather — ${d.name}, ${d.sys?.country || ''}*\n\n🌡️ ${d.main.temp}°C (feels ${d.main.feels_like}°C)\n☁️ ${d.weather[0]?.description}\n💧 Humidity: ${d.main.humidity}%\n💨 Wind: ${d.wind.speed} m/s`;
      } catch { return '❌ Could not fetch weather. Check the city name.'; }
    } },
  { name: 'time', description: 'Current time', category: 'tools', usage: '.time [timezone]',
    execute: (args) => {
      const tz = args[0] || 'Asia/Karachi';
      try {
        const t = new Date().toLocaleTimeString('en-GB', { timeZone: tz, hour: '2-digit', minute: '2-digit', second: '2-digit' });
        return `🕐 *Time (${tz}):* ${t}`;
      } catch { return '❌ Unknown timezone. Example: .time Asia/Dubai'; }
    } },
  { name: 'date', description: "Today's date", category: 'tools', usage: '.date',
    execute: () => `📅 *Today:* ${new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' })}` },
  { name: 'currency', description: 'Convert currency (free rates)', category: 'tools', usage: '.currency <amount> <from> <to>  (e.g. .currency 100 USD PKR)',
    execute: async (args) => {
      if (args.length < 3) return '💱 Usage: .currency <amount> <from> <to>\nExample: .currency 100 USD PKR';
      const [amt, from, to] = [parseFloat(args[0]), args[1].toUpperCase(), args[2].toUpperCase()];
      if (isNaN(amt)) return '❌ Amount must be a number.';
      try {
        const d = await fetchJson(`https://open.er-api.com/v6/latest/${from}`);
        const rate = d?.rates?.[to];
        if (!rate) throw new Error('rate');
        return `💱 *${amt} ${from} = ${(amt * rate).toFixed(2)} ${to}*\n(Rate: 1 ${from} = ${rate} ${to})`;
      } catch { return '❌ Could not fetch rates. Check currency codes (e.g. USD, PKR, EUR).'; }
    } },
  { name: 'password', description: 'Generate a strong password', category: 'tools', usage: '.password [length]',
    execute: (args) => {
      const len = Math.max(6, Math.min(64, parseInt(args[0], 10) || 16));
      const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*';
      let pw = '';
      for (let i = 0; i < len; i++) pw += chars[crypto.randomInt(chars.length)];
      return `🔐 *Generated password (${len} chars):*\n\`${pw}\`\n⚠️ Keep it secret — don’t share it!`;
    } },
  { name: 'uuid', description: 'Generate a UUID', category: 'tools', usage: '.uuid',
    execute: () => `🆔 *UUID:*\n\`${crypto.randomUUID()}\`` },
  { name: 'base64enc', description: 'Encode text to Base64', category: 'tools', usage: '.base64enc <text>',
    execute: (args) => { const e = needArgs(args, '.base64enc <text>'); return e || `📦 *Base64:*\n\`${Buffer.from(args.join(' '), 'utf8').toString('base64')}\``; } },
  { name: 'base64dec', description: 'Decode Base64 text', category: 'tools', usage: '.base64dec <base64>',
    execute: (args) => {
      const e = needArgs(args, '.base64dec <base64>'); if (e) return e;
      try { return `📦 *Decoded:*\n${Buffer.from(args[0], 'base64').toString('utf8')}`; }
      catch { return '❌ Invalid Base64 input.'; }
    } },
  { name: 'urlencode', description: 'URL-encode text', category: 'tools', usage: '.urlencode <text>',
    execute: (args) => { const e = needArgs(args, '.urlencode <text>'); return e || `🔗 *Encoded:*\n\`${encodeURIComponent(args.join(' '))}\``; } },
  { name: 'urldecode', description: 'URL-decode text', category: 'tools', usage: '.urldecode <text>',
    execute: (args) => {
      const e = needArgs(args, '.urldecode <text>'); if (e) return e;
      try { return `🔗 *Decoded:*\n${decodeURIComponent(args.join(' '))}`; }
      catch { return '❌ Invalid URL-encoded input.'; }
    } },
  { name: 'morse', description: 'Text ⇄ Morse code', category: 'tools', usage: '.morse <text>  or  .morse decode <code>',
    execute: (args) => {
      if (!args.length) return '📡 Usage: .morse <text>  or  .morse decode <morse code>';
      if (args[0].toLowerCase() === 'decode') return `📡 *Decoded:*\n${fromMorse(args.slice(1).join(' ')) || '(empty)'}`;
      return `📡 *Morse:*\n${toMorse(args.join(' '))}`;
    } },
  { name: 'binary', description: 'Convert text to binary', category: 'tools', usage: '.binary <text>',
    execute: (args) => { const e = needArgs(args, '.binary <text>'); return e || `💻 *Binary:*\n${args.join(' ').split('').map((c) => c.charCodeAt(0).toString(2).padStart(8, '0')).join(' ')}`; } },
  { name: 'hex', description: 'Convert text to hex', category: 'tools', usage: '.hex <text>',
    execute: (args) => { const e = needArgs(args, '.hex <text>'); return e || `🔢 *Hex:*\n\`${Buffer.from(args.join(' '), 'utf8').toString('hex')}\``; } },
  { name: 'charcount', description: 'Count characters', category: 'tools', usage: '.charcount <text>',
    execute: (args) => { const e = needArgs(args, '.charcount <text>'); if (e) return e; const t = args.join(' '); return `🔤 Characters: *${t.length}* (without spaces: ${t.replace(/\s/g, '').length})`; } },
  { name: 'wordcount', description: 'Count words', category: 'tools', usage: '.wordcount <text>',
    execute: (args) => { const e = needArgs(args, '.wordcount <text>'); if (e) return e; const w = args.join(' ').trim().split(/\s+/); return `📝 Words: *${w.length}*`; } },
  { name: 'color', description: 'Random color with hex code', category: 'tools', usage: '.color',
    execute: () => {
      const hex = '#' + crypto.randomInt(0xffffff).toString(16).padStart(6, '0');
      return `🎨 *Random color:* ${hex}\nPreview: https://www.colorhexa.com/${hex.slice(1)}`;
    } },
  { name: 'ipinfo', description: 'Look up an IP address (free API)', category: 'tools', usage: '.ipinfo <ip>',
    execute: async (args) => {
      const e = needArgs(args, '.ipinfo <ip>'); if (e) return e;
      try {
        const d = await fetchJson(`http://ip-api.com/json/${encodeURIComponent(args[0])}?fields=status,country,city,isp,query`);
        if (d.status !== 'success') throw new Error('fail');
        return `🌐 *IP info — ${d.query}*\n\n🏳️ Country: ${d.country}\n🏙️ City: ${d.city}\n📡 ISP: ${d.isp}`;
      } catch { return '❌ Could not look up that IP.'; }
    } },
  { name: 'timer', description: 'Set a quick timer (max 60 min)', category: 'tools', usage: '.timer <minutes> [label]',
    execute: (args, ctx) => {
      const mins = parseFloat(args[0]);
      if (isNaN(mins) || mins <= 0 || mins > 60) return '⏲️ Usage: .timer <minutes up to 60> [label]';
      const label = args.slice(1).join(' ') || 'Timer';
      setTimeout(() => { try { ctx.send(`⏰ *${label}* — time’s up! (${mins} min)`); } catch {} }, mins * 60000);
      return `⏲️ Timer set for *${mins} minute(s)* — "${label}". I’ll message you here when it rings!`;
    } },
  { name: 'reminder', description: 'Remind yourself later (max 24h)', category: 'tools', usage: '.reminder <minutes> <message>',
    execute: (args, ctx) => {
      const mins = parseFloat(args[0]);
      const msg = args.slice(1).join(' ');
      if (isNaN(mins) || mins <= 0 || mins > 1440 || !msg) return '⏰ Usage: .reminder <minutes up to 1440> <message>';
      setTimeout(() => { try { ctx.send(`🔔 *Reminder:* ${msg}`); } catch {} }, mins * 60000);
      return `🔔 Reminder saved! I’ll remind you in *${mins} minute(s)*.`;
    } },
  { name: 'note', description: 'Save / list / clear notes', category: 'tools', usage: '.note add <text> | .note list | .note clear',
    execute: (args, ctx) => {
      const notes = userBox('notes', ctx.from);
      const sub = (args[0] || 'list').toLowerCase();
      if (sub === 'add') {
        const t = args.slice(1).join(' ');
        if (!t) return '📝 Usage: .note add <text>';
        notes.push(t);
        return `📝 Note #${notes.length} saved!`;
      }
      if (sub === 'clear') { store.notes[ctx.from] = []; return '🗑️ All your notes cleared.'; }
      if (!notes.length) return '📝 You have no notes. Use: .note add <text>';
      return '📝 *Your notes:*\n\n' + notes.map((n, i) => `${i + 1}. ${n}`).join('\n');
    } },
  { name: 'todo', description: 'To-do list manager', category: 'tools', usage: '.todo add <task> | .todo list | .todo done <n> | .todo clear',
    execute: (args, ctx) => {
      const todos = userBox('todos', ctx.from);
      const sub = (args[0] || 'list').toLowerCase();
      if (sub === 'add') {
        const t = args.slice(1).join(' ');
        if (!t) return '✅ Usage: .todo add <task>';
        todos.push({ text: t, done: false });
        return `✅ Task #${todos.length} added!`;
      }
      if (sub === 'done') {
        const n = parseInt(args[1], 10);
        if (!todos[n - 1]) return '❌ Task number not found.';
        todos[n - 1].done = true;
        return `🎉 Task #${n} marked done!`;
      }
      if (sub === 'clear') { store.todos[ctx.from] = []; return '🗑️ To-do list cleared.'; }
      if (!todos.length) return '✅ No tasks. Use: .todo add <task>';
      return '✅ *Your to-do list:*\n\n' + todos.map((t, i) => `${t.done ? '☑️' : '⬜'} ${i + 1}. ${t.text}`).join('\n');
    } },
  { name: 'poll', description: 'Create a simple poll', category: 'tools', usage: '.poll <question> | <opt1> | <opt2> ...',
    execute: (args) => {
      const parts = args.join(' ').split('|').map((p) => p.trim()).filter(Boolean);
      if (parts.length < 3) return '📊 Usage: .poll <question> | <option1> | <option2> ...';
      const [q, ...opts] = parts;
      return `📊 *POLL:* ${q}\n\n${opts.map((o, i) => `${['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣'][i] || '🔹'} ${o}`).join('\n')}\n\n_Reply with your choice!_`;
    } },
  { name: 'langdetect', description: 'Detect Urdu / Roman Urdu / English', category: 'tools', usage: '.langdetect <text>',
    execute: (args) => {
      const e = needArgs(args, '.langdetect <text>'); if (e) return e;
      const t = args.join(' ');
      if (/[\u0600-\u06FF]/.test(t)) return '🔎 Detected language: *Urdu (اردو)* 🇵🇰';
      const words = t.toLowerCase().split(/\W+/);
      const hits = words.filter((w) => ROMAN_URDU_WORDS.includes(w)).length;
      if (hits >= 2 || (hits >= 1 && words.length <= 4)) return '🔎 Detected language: *Roman Urdu* 🇵🇰';
      return '🔎 Detected language: *English* 🇬🇧';
    } },
  { name: 'hash', description: 'SHA-256 / MD5 hash of text', category: 'tools', usage: '.hash [md5] <text>',
    execute: (args) => {
      let algo = 'sha256';
      let text = args.join(' ');
      if (args[0]?.toLowerCase() === 'md5') { algo = 'md5'; text = args.slice(1).join(' '); }
      if (!text) return '🔑 Usage: .hash [md5] <text>';
      return `🔑 *${algo.toUpperCase()}:*\n\`${crypto.createHash(algo).update(text).digest('hex')}\``;
    } },
  { name: 'caseconv', description: 'Change text case', category: 'tools', usage: '.caseconv <upper|lower|title> <text>',
    execute: (args) => {
      const mode = (args[0] || '').toLowerCase();
      const text = args.slice(1).join(' ');
      if (!['upper', 'lower', 'title'].includes(mode) || !text) return '🔠 Usage: .caseconv <upper|lower|title> <text>';
      const out = mode === 'upper' ? text.toUpperCase() : mode === 'lower' ? text.toLowerCase()
        : text.toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase());
      return `🔠 *${mode}:*\n${out}`;
    } },
];

module.exports = commands;
